### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by Kumicoo** [terascripter/undrm-script#1]
What does this do and how do i use it?

**Comment by Kumicoo** [comment]
Do i need to buy a bern script and i can use this to share with my friends or what?

**Comment by terascripter** [comment]
yes, or you can buy from me cheaper, undrmed, and shareable

**Comment by Kumicoo** [comment]
Where do i contact you? Discord? Please give me your discord data then. Don't want to share it, just interested in them.

**Comment by terascripter** [comment]
Send an email to: menegragames@gmail.com with your discord tag and I will contact you
